version: '3.2'
services:
  bitcoin-abc-conf:
    build: extra/compose
    volumes:
      - bitcoin-abc-data-dir:/data
      - bch-conf-dir:/home/ows/config
  bitcoin-abc:
    image: "owstack/bitcoin-abc:0.14.6-ows"
    user: root
    command: "/usr/local/bin/bitcoind -datadir=/data"
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin-abc-data-dir:/data
    depends_on:
      - "bitcoin-abc-conf"
  bcc-node:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - "bitcoin-abc"
    volumes:
    #   - bitcoin-abc-data-dir:/data
      - bch-conf-dir:/home/ows/config
    command: "bch-node start -c /home/ows/config"
    # command: "cat /home/ows/config/bch-node.json"
volumes:
  bitcoin-abc-data-dir:
  bch-conf-dir:
